// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sobel_filter_HH_
#define _sobel_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct sobel_filter : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<18> > in_r_address0;
    sc_out< sc_logic > in_r_ce0;
    sc_in< sc_lv<8> > in_r_q0;
    sc_out< sc_lv<18> > in_r_address1;
    sc_out< sc_logic > in_r_ce1;
    sc_in< sc_lv<8> > in_r_q1;
    sc_out< sc_lv<18> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<8> > out_r_d0;


    // Module declarations
    sobel_filter(sc_module_name name);
    SC_HAS_PROCESS(sobel_filter);

    ~sobel_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > reg_158;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<8> > reg_163;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<18> > shl_ln8_fu_174_p3;
    sc_signal< sc_lv<18> > shl_ln8_reg_589;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln6_fu_168_p2;
    sc_signal< sc_lv<19> > zext_ln8_fu_188_p1;
    sc_signal< sc_lv<19> > zext_ln8_reg_598;
    sc_signal< sc_lv<19> > zext_ln8_1_fu_198_p1;
    sc_signal< sc_lv<19> > zext_ln8_1_reg_603;
    sc_signal< sc_lv<10> > zext_ln7_fu_202_p1;
    sc_signal< sc_lv<10> > zext_ln7_reg_608;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln7_fu_214_p2;
    sc_signal< sc_lv<19> > add_ln8_4_fu_259_p2;
    sc_signal< sc_lv<19> > add_ln8_4_reg_626;
    sc_signal< sc_lv<19> > add_ln8_7_fu_264_p2;
    sc_signal< sc_lv<19> > add_ln8_7_reg_631;
    sc_signal< sc_lv<9> > i_fu_269_p2;
    sc_signal< sc_lv<10> > add_ln8_5_fu_279_p2;
    sc_signal< sc_lv<10> > add_ln8_5_reg_646;
    sc_signal< sc_lv<10> > add_ln8_10_fu_345_p2;
    sc_signal< sc_lv<10> > add_ln8_10_reg_666;
    sc_signal< sc_lv<9> > sub_ln9_fu_351_p2;
    sc_signal< sc_lv<9> > sub_ln9_reg_671;
    sc_signal< sc_lv<8> > in_load_5_reg_676;
    sc_signal< sc_lv<8> > in_load_6_reg_693;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<8> > in_load_7_reg_698;
    sc_signal< sc_lv<10> > sub_ln9_1_fu_409_p2;
    sc_signal< sc_lv<10> > sub_ln9_1_reg_703;
    sc_signal< sc_lv<8> > add_ln12_fu_561_p2;
    sc_signal< sc_lv<8> > add_ln12_reg_708;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<9> > j_fu_580_p2;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<9> > i_0_reg_134;
    sc_signal< sc_lv<9> > j_0_reg_146;
    sc_signal< sc_lv<64> > zext_ln8_2_fu_235_p1;
    sc_signal< sc_lv<64> > zext_ln8_4_fu_254_p1;
    sc_signal< sc_lv<64> > zext_ln8_6_fu_275_p1;
    sc_signal< sc_lv<64> > zext_ln8_8_fu_293_p1;
    sc_signal< sc_lv<64> > zext_ln8_10_fu_318_p1;
    sc_signal< sc_lv<64> > zext_ln8_11_fu_330_p1;
    sc_signal< sc_lv<64> > zext_ln9_fu_374_p1;
    sc_signal< sc_lv<64> > zext_ln9_3_fu_388_p1;
    sc_signal< sc_lv<64> > zext_ln12_fu_575_p1;
    sc_signal< sc_lv<18> > or_ln8_fu_182_p2;
    sc_signal< sc_lv<18> > or_ln8_1_fu_192_p2;
    sc_signal< sc_lv<11> > zext_ln7_2_fu_210_p1;
    sc_signal< sc_lv<11> > add_ln8_fu_220_p2;
    sc_signal< sc_lv<18> > sext_ln8_fu_226_p1;
    sc_signal< sc_lv<18> > add_ln8_1_fu_230_p2;
    sc_signal< sc_lv<9> > add_ln8_2_fu_240_p2;
    sc_signal< sc_lv<18> > add_ln8_3_fu_246_p3;
    sc_signal< sc_lv<19> > zext_ln7_1_fu_206_p1;
    sc_signal< sc_lv<18> > sext_ln8_1_fu_284_p1;
    sc_signal< sc_lv<18> > add_ln8_6_fu_288_p2;
    sc_signal< sc_lv<9> > shl_ln8_1_fu_302_p3;
    sc_signal< sc_lv<18> > zext_ln8_14_fu_322_p1;
    sc_signal< sc_lv<18> > add_ln8_8_fu_325_p2;
    sc_signal< sc_lv<9> > zext_ln8_3_fu_298_p1;
    sc_signal< sc_lv<9> > zext_ln8_7_fu_314_p1;
    sc_signal< sc_lv<9> > add_ln8_9_fu_335_p2;
    sc_signal< sc_lv<10> > zext_ln8_17_fu_341_p1;
    sc_signal< sc_lv<10> > zext_ln8_5_fu_310_p1;
    sc_signal< sc_lv<10> > or_ln9_fu_357_p3;
    sc_signal< sc_lv<18> > sext_ln9_fu_365_p1;
    sc_signal< sc_lv<18> > add_ln9_fu_369_p2;
    sc_signal< sc_lv<18> > zext_ln9_2_fu_379_p1;
    sc_signal< sc_lv<18> > add_ln9_1_fu_383_p2;
    sc_signal< sc_lv<10> > sext_ln9_1_fu_400_p1;
    sc_signal< sc_lv<10> > zext_ln8_9_fu_393_p1;
    sc_signal< sc_lv<10> > add_ln9_2_fu_403_p2;
    sc_signal< sc_lv<10> > zext_ln8_16_fu_397_p1;
    sc_signal< sc_lv<9> > shl_ln8_2_fu_419_p3;
    sc_signal< sc_lv<11> > zext_ln8_12_fu_415_p1;
    sc_signal< sc_lv<11> > zext_ln8_18_fu_434_p1;
    sc_signal< sc_lv<11> > sub_ln8_fu_437_p2;
    sc_signal< sc_lv<11> > zext_ln8_15_fu_431_p1;
    sc_signal< sc_lv<11> > add_ln8_11_fu_453_p2;
    sc_signal< sc_lv<11> > zext_ln8_13_fu_427_p1;
    sc_signal< sc_lv<9> > shl_ln9_1_fu_465_p3;
    sc_signal< sc_lv<9> > shl_ln9_fu_476_p3;
    sc_signal< sc_lv<11> > zext_ln9_1_fu_472_p1;
    sc_signal< sc_lv<11> > sext_ln9_2_fu_487_p1;
    sc_signal< sc_lv<11> > add_ln9_3_fu_490_p2;
    sc_signal< sc_lv<11> > zext_ln9_4_fu_483_p1;
    sc_signal< sc_lv<11> > gx_sum_fu_459_p2;
    sc_signal< sc_lv<8> > trunc_ln8_fu_449_p1;
    sc_signal< sc_lv<8> > shl_ln8_3_fu_443_p2;
    sc_signal< sc_lv<8> > add_ln10_1_fu_510_p2;
    sc_signal< sc_lv<8> > add_ln10_fu_516_p2;
    sc_signal< sc_lv<1> > tmp_fu_502_p3;
    sc_signal< sc_lv<8> > sub_ln10_fu_521_p2;
    sc_signal< sc_lv<11> > gy_sum_fu_496_p2;
    sc_signal< sc_lv<8> > trunc_ln11_fu_543_p1;
    sc_signal< sc_lv<1> > tmp_1_fu_535_p3;
    sc_signal< sc_lv<8> > sub_ln11_fu_547_p2;
    sc_signal< sc_lv<8> > select_ln11_fu_553_p3;
    sc_signal< sc_lv<8> > select_ln10_fu_527_p3;
    sc_signal< sc_lv<18> > add_ln12_1_fu_567_p3;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<9> ap_const_lv9_1FF;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<18> ap_const_lv18_1FF;
    static const sc_lv<18> ap_const_lv18_1;
    static const sc_lv<11> ap_const_lv11_5FF;
    static const sc_lv<10> ap_const_lv10_201;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<8> ap_const_lv8_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln10_1_fu_510_p2();
    void thread_add_ln10_fu_516_p2();
    void thread_add_ln12_1_fu_567_p3();
    void thread_add_ln12_fu_561_p2();
    void thread_add_ln8_10_fu_345_p2();
    void thread_add_ln8_11_fu_453_p2();
    void thread_add_ln8_1_fu_230_p2();
    void thread_add_ln8_2_fu_240_p2();
    void thread_add_ln8_3_fu_246_p3();
    void thread_add_ln8_4_fu_259_p2();
    void thread_add_ln8_5_fu_279_p2();
    void thread_add_ln8_6_fu_288_p2();
    void thread_add_ln8_7_fu_264_p2();
    void thread_add_ln8_8_fu_325_p2();
    void thread_add_ln8_9_fu_335_p2();
    void thread_add_ln8_fu_220_p2();
    void thread_add_ln9_1_fu_383_p2();
    void thread_add_ln9_2_fu_403_p2();
    void thread_add_ln9_3_fu_490_p2();
    void thread_add_ln9_fu_369_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_gx_sum_fu_459_p2();
    void thread_gy_sum_fu_496_p2();
    void thread_i_fu_269_p2();
    void thread_icmp_ln6_fu_168_p2();
    void thread_icmp_ln7_fu_214_p2();
    void thread_in_r_address0();
    void thread_in_r_address1();
    void thread_in_r_ce0();
    void thread_in_r_ce1();
    void thread_j_fu_580_p2();
    void thread_or_ln8_1_fu_192_p2();
    void thread_or_ln8_fu_182_p2();
    void thread_or_ln9_fu_357_p3();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_select_ln10_fu_527_p3();
    void thread_select_ln11_fu_553_p3();
    void thread_sext_ln8_1_fu_284_p1();
    void thread_sext_ln8_fu_226_p1();
    void thread_sext_ln9_1_fu_400_p1();
    void thread_sext_ln9_2_fu_487_p1();
    void thread_sext_ln9_fu_365_p1();
    void thread_shl_ln8_1_fu_302_p3();
    void thread_shl_ln8_2_fu_419_p3();
    void thread_shl_ln8_3_fu_443_p2();
    void thread_shl_ln8_fu_174_p3();
    void thread_shl_ln9_1_fu_465_p3();
    void thread_shl_ln9_fu_476_p3();
    void thread_sub_ln10_fu_521_p2();
    void thread_sub_ln11_fu_547_p2();
    void thread_sub_ln8_fu_437_p2();
    void thread_sub_ln9_1_fu_409_p2();
    void thread_sub_ln9_fu_351_p2();
    void thread_tmp_1_fu_535_p3();
    void thread_tmp_fu_502_p3();
    void thread_trunc_ln11_fu_543_p1();
    void thread_trunc_ln8_fu_449_p1();
    void thread_zext_ln12_fu_575_p1();
    void thread_zext_ln7_1_fu_206_p1();
    void thread_zext_ln7_2_fu_210_p1();
    void thread_zext_ln7_fu_202_p1();
    void thread_zext_ln8_10_fu_318_p1();
    void thread_zext_ln8_11_fu_330_p1();
    void thread_zext_ln8_12_fu_415_p1();
    void thread_zext_ln8_13_fu_427_p1();
    void thread_zext_ln8_14_fu_322_p1();
    void thread_zext_ln8_15_fu_431_p1();
    void thread_zext_ln8_16_fu_397_p1();
    void thread_zext_ln8_17_fu_341_p1();
    void thread_zext_ln8_18_fu_434_p1();
    void thread_zext_ln8_1_fu_198_p1();
    void thread_zext_ln8_2_fu_235_p1();
    void thread_zext_ln8_3_fu_298_p1();
    void thread_zext_ln8_4_fu_254_p1();
    void thread_zext_ln8_5_fu_310_p1();
    void thread_zext_ln8_6_fu_275_p1();
    void thread_zext_ln8_7_fu_314_p1();
    void thread_zext_ln8_8_fu_293_p1();
    void thread_zext_ln8_9_fu_393_p1();
    void thread_zext_ln8_fu_188_p1();
    void thread_zext_ln9_1_fu_472_p1();
    void thread_zext_ln9_2_fu_379_p1();
    void thread_zext_ln9_3_fu_388_p1();
    void thread_zext_ln9_4_fu_483_p1();
    void thread_zext_ln9_fu_374_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
