// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Cb_HH_
#define _Cb_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Cb_dadddsub_64ns_bkb.h"
#include "Cb_dmul_64ns_64nscud.h"
#include "Cb_sitodp_32ns_64dEe.h"

namespace ap_rtl {

struct Cb : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > R;
    sc_in< sc_lv<8> > G;
    sc_in< sc_lv<8> > B;
    sc_out< sc_lv<8> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    Cb(sc_module_name name);
    SC_HAS_PROCESS(Cb);

    ~Cb();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Cb_dadddsub_64ns_bkb<1,5,64,64,64>* Cb_dadddsub_64ns_bkb_U1;
    Cb_dmul_64ns_64nscud<1,5,64,64,64>* Cb_dmul_64ns_64nscud_U2;
    Cb_dmul_64ns_64nscud<1,5,64,64,64>* Cb_dmul_64ns_64nscud_U3;
    Cb_sitodp_32ns_64dEe<1,5,32,64>* Cb_sitodp_32ns_64dEe_U4;
    Cb_sitodp_32ns_64dEe<1,5,32,64>* Cb_sitodp_32ns_64dEe_U5;
    sc_signal< sc_lv<27> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_100_p1;
    sc_signal< sc_lv<64> > reg_106;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > and_ln10_4_reg_341;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > grp_fu_89_p2;
    sc_signal< sc_lv<64> > reg_111;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > grp_fu_84_p2;
    sc_signal< sc_lv<64> > reg_117;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<1> > and_ln10_4_fu_182_p2;
    sc_signal< sc_lv<32> > zext_ln16_fu_188_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > grp_fu_103_p1;
    sc_signal< sc_lv<64> > tmp_4_reg_356;
    sc_signal< sc_lv<32> > zext_ln16_2_fu_196_p1;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > grp_fu_94_p2;
    sc_signal< sc_lv<64> > tmp_5_reg_366;
    sc_signal< sc_lv<11> > tmp_V_reg_371;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<52> > tmp_V_1_fu_214_p1;
    sc_signal< sc_lv<52> > tmp_V_1_reg_377;
    sc_signal< sc_lv<64> > grp_fu_84_p0;
    sc_signal< sc_lv<64> > grp_fu_84_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<64> > grp_fu_89_p1;
    sc_signal< sc_lv<32> > grp_fu_100_p0;
    sc_signal< sc_lv<32> > grp_fu_103_p0;
    sc_signal< sc_lv<1> > icmp_ln10_1_fu_128_p2;
    sc_signal< sc_lv<1> > icmp_ln10_2_fu_134_p2;
    sc_signal< sc_lv<1> > and_ln10_fu_158_p2;
    sc_signal< sc_lv<1> > icmp_ln10_fu_122_p2;
    sc_signal< sc_lv<1> > icmp_ln10_4_fu_146_p2;
    sc_signal< sc_lv<1> > icmp_ln10_5_fu_152_p2;
    sc_signal< sc_lv<1> > and_ln10_2_fu_170_p2;
    sc_signal< sc_lv<1> > icmp_ln10_3_fu_140_p2;
    sc_signal< sc_lv<1> > and_ln10_3_fu_176_p2;
    sc_signal< sc_lv<1> > and_ln10_1_fu_164_p2;
    sc_signal< sc_lv<64> > p_Val2_s_fu_200_p1;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<54> > mantissa_V_fu_218_p4;
    sc_signal< sc_lv<12> > zext_ln502_fu_231_p1;
    sc_signal< sc_lv<12> > add_ln502_fu_234_p2;
    sc_signal< sc_lv<11> > sub_ln1311_fu_248_p2;
    sc_signal< sc_lv<1> > isNeg_fu_240_p3;
    sc_signal< sc_lv<12> > sext_ln1311_fu_253_p1;
    sc_signal< sc_lv<12> > ush_fu_257_p3;
    sc_signal< sc_lv<32> > sext_ln1311_1_fu_265_p1;
    sc_signal< sc_lv<54> > zext_ln1285_fu_273_p1;
    sc_signal< sc_lv<113> > zext_ln682_fu_227_p1;
    sc_signal< sc_lv<113> > zext_ln1287_fu_269_p1;
    sc_signal< sc_lv<54> > r_V_fu_277_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_289_p3;
    sc_signal< sc_lv<113> > r_V_1_fu_283_p2;
    sc_signal< sc_lv<8> > zext_ln662_fu_297_p1;
    sc_signal< sc_lv<8> > tmp_2_fu_301_p4;
    sc_signal< sc_lv<8> > val_V_fu_311_p3;
    sc_signal< sc_lv<2> > grp_fu_84_opcode;
    sc_signal< sc_lv<27> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<27> ap_ST_fsm_state1;
    static const sc_lv<27> ap_ST_fsm_state2;
    static const sc_lv<27> ap_ST_fsm_state3;
    static const sc_lv<27> ap_ST_fsm_state4;
    static const sc_lv<27> ap_ST_fsm_state5;
    static const sc_lv<27> ap_ST_fsm_state6;
    static const sc_lv<27> ap_ST_fsm_state7;
    static const sc_lv<27> ap_ST_fsm_state8;
    static const sc_lv<27> ap_ST_fsm_state9;
    static const sc_lv<27> ap_ST_fsm_state10;
    static const sc_lv<27> ap_ST_fsm_state11;
    static const sc_lv<27> ap_ST_fsm_state12;
    static const sc_lv<27> ap_ST_fsm_state13;
    static const sc_lv<27> ap_ST_fsm_state14;
    static const sc_lv<27> ap_ST_fsm_state15;
    static const sc_lv<27> ap_ST_fsm_state16;
    static const sc_lv<27> ap_ST_fsm_state17;
    static const sc_lv<27> ap_ST_fsm_state18;
    static const sc_lv<27> ap_ST_fsm_state19;
    static const sc_lv<27> ap_ST_fsm_state20;
    static const sc_lv<27> ap_ST_fsm_state21;
    static const sc_lv<27> ap_ST_fsm_state22;
    static const sc_lv<27> ap_ST_fsm_state23;
    static const sc_lv<27> ap_ST_fsm_state24;
    static const sc_lv<27> ap_ST_fsm_state25;
    static const sc_lv<27> ap_ST_fsm_state26;
    static const sc_lv<27> ap_ST_fsm_state27;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<64> ap_const_lv64_4060000000000000;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<64> ap_const_lv64_BFC2F1A9FBE76C8B;
    static const sc_lv<64> ap_const_lv64_3FDC189374BC6A7F;
    static const sc_lv<64> ap_const_lv64_3FD29FBE76C8B439;
    static const sc_lv<8> ap_const_lv8_42;
    static const sc_lv<8> ap_const_lv8_1A;
    static const sc_lv<8> ap_const_lv8_4C;
    static const sc_lv<8> ap_const_lv8_24;
    static const sc_lv<8> ap_const_lv8_55;
    static const sc_lv<8> ap_const_lv8_2D;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_3C;
    static const sc_lv<8> ap_const_lv8_85;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_add_ln502_fu_234_p2();
    void thread_and_ln10_1_fu_164_p2();
    void thread_and_ln10_2_fu_170_p2();
    void thread_and_ln10_3_fu_176_p2();
    void thread_and_ln10_4_fu_182_p2();
    void thread_and_ln10_fu_158_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_100_p0();
    void thread_grp_fu_103_p0();
    void thread_grp_fu_84_opcode();
    void thread_grp_fu_84_p0();
    void thread_grp_fu_84_p1();
    void thread_grp_fu_89_p1();
    void thread_icmp_ln10_1_fu_128_p2();
    void thread_icmp_ln10_2_fu_134_p2();
    void thread_icmp_ln10_3_fu_140_p2();
    void thread_icmp_ln10_4_fu_146_p2();
    void thread_icmp_ln10_5_fu_152_p2();
    void thread_icmp_ln10_fu_122_p2();
    void thread_isNeg_fu_240_p3();
    void thread_mantissa_V_fu_218_p4();
    void thread_p_Val2_s_fu_200_p1();
    void thread_r_V_1_fu_283_p2();
    void thread_r_V_fu_277_p2();
    void thread_sext_ln1311_1_fu_265_p1();
    void thread_sext_ln1311_fu_253_p1();
    void thread_sub_ln1311_fu_248_p2();
    void thread_tmp_10_fu_289_p3();
    void thread_tmp_2_fu_301_p4();
    void thread_tmp_V_1_fu_214_p1();
    void thread_ush_fu_257_p3();
    void thread_val_V_fu_311_p3();
    void thread_zext_ln1285_fu_273_p1();
    void thread_zext_ln1287_fu_269_p1();
    void thread_zext_ln16_2_fu_196_p1();
    void thread_zext_ln16_fu_188_p1();
    void thread_zext_ln502_fu_231_p1();
    void thread_zext_ln662_fu_297_p1();
    void thread_zext_ln682_fu_227_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
